"""shows.id

Revision ID: 27565708c704
Revises: db28a808b090
Create Date: 2025-04-02 17:16:16.395490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27565708c704'
down_revision: Union[str, None] = 'db28a808b090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('characters', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'characters', 'shows', ['show_id'], ['id'])
    op.alter_column('shows', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.alter_column('characters', 'show_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('characters', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
