"""New Migration

Revision ID: db28a808b090
Revises: 
Create Date: 2025-04-02 16:21:56.551294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db28a808b090'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('characters', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('characters_name_key', 'characters', type_='unique')
    op.create_index(op.f('ix_characters_id'), 'characters', ['id'], unique=False)
    op.drop_constraint('characters_show_id_fkey', 'characters', type_='foreignkey')
    op.alter_column('shows', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint('shows_name_key', 'shows', type_='unique')
    op.create_index(op.f('ix_shows_id'), 'shows', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shows_id'), table_name='shows')
    op.create_unique_constraint('shows_name_key', 'shows', ['name'])
    op.alter_column('shows', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key('characters_show_id_fkey', 'characters', 'shows', ['show_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_characters_id'), table_name='characters')
    op.create_unique_constraint('characters_name_key', 'characters', ['name'])
    op.alter_column('characters', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
