
const Tropes = {

    Romance: ['Friends to Lovers', 'Enemies to Lovers', 'Forbidden Love', 'Fake Relationship', 'Love Triangle', 'Unrequited Love', 'Second Chance Romance', 'Childhood Sweethearts', 'Slow Burn', 'Soulmates/Destined', 'Forced Proximity', 'Marriage of Convenience', 'Accidental Pregnancy', 'Office Romance', 'Holiday Romance', 'Amnesia', 'Reunion Romance', 'The Bet', 'Secret Relationship', 'Undercover Relationship', 'The Cynic Falls for the Romantic', 'The Protector', 'The Broken Hero/Heroine', 'The Secret Billionaire', 'The Single Parent', 'The Ugly Duckling Makeover', 'Miscommunication', 'Love/Hate Relationship', 'Jealousy', 'Rivals Turned Lovers', 'Class Differences', 'Sacrificing For Love', 'Secret Past', 'Royal Romance', 'College/High School Romance', 'Road Trip Romance', 'Summer Fling', 'The Playboy/Playgirl', 'Grumpy/Sunshine', 'Friends with Benefits', 'One Night Stand to More', 'The Bodyguard and The VIP', 'The Forbidden Boss/Employee Romance', 'The Reformed Bad Boy/Girl', 'Only One Bed', 'The Heat of the Moment', 'Accidental Touches', '"Teach Me" Dynamic', 'Shared Secret', 'The Spicy Dare/Bet', 'The Masquerade or Disguise', 'Overhearing a confession', 'The Alpha', 'Virgin/Inexperienced Partner', 'The Seductress/Seducer', 'The Brooding Loner', 'The Dom/Sub Dynamic', 'The Shy One and The Charmer', 'The Protective Lover', 'The Wild Card', 'The Longing Look', 'Unresolved Sexual Tension','Thr Accidental Kiss', 'The Push Pull Dynamic', 'Taboo or illicit desire', 'The Unexpected Confession', 'Jealousy and Possessiveness', 'The Interrupted Moment', 'Healing through Intimacy', 'The Exploration of Kinks', 'The First Time', "'I shouldn't Want you'", 'The Secret Affair', 'The Reunion Hookup', 'The Bond of Trust', 'The Power of Vulnerability', 'The Tension of Restraint', 'The Role Reversal', 'The War Bride/Groom', 'The Nobel and The Commoner', "The Pirate's Captive", 'A Reluctant Fiance', 'The Disguised Lover', 'The Tragic Romance', 'The Star-Crossed Lovers'],

    Action: ['The Reluctant Hero', 'The Chosen One', 'The Lone Wolf', 'The Anti-Hero', 'The Mentor', 'The Femme Fatale', 'The Villian with a Code', 'The Sidekick', 'The Underdog', 'The Redemption Seeker', 'Revenge Quest', 'Save the Hostages', 'The Rescue Mission', 'Heist and Break-in', 'The Final Showdown', 'The MacGuffin Chase', 'Race Against Time', 'Betrayal Twist', 'The Rags-to-Riches Journey', 'The Double-Cross', "Hero's Sacrifice", 'The Countdown', 'Trapped in Enemy Territory', 'Post-Apocolyptic World', 'Warfare', 'The Duel', 'Train Heist', 'Underwater Escape'],

    Adventure: ['The Quest', 'The Journey', 'Lost Worlds', 'Escape Adventure', 'Survival', 'Treasure Hunt', 'The Race', 'The Homecoming', 'The Band of Misfits', 'The Dashing Rogue', 'The Orphan Hero', 'The Noble Savage', 'The Uncharted Land', 'The Desert', 'The Jungle', 'The High Seas', 'Underground Realms', 'The Mountain Peak', 'The Remote Village', 'The Forbidden Zone', 'The Wasteland', 'The puzzle or Riddle', 'The Trap', 'The Deadly Creature', 'The Bridge Collapse', 'The Chase Scene', 'The Moral Dilema', 'The Impossible Task', 'The Ambush', 'The Power of Friendship', 'Discovery and Wonder', 'The Legend Comes to Life', 'Redemption', 'Close calls'],

    Comedy: ['Body-swap', 'Beach Episode', 'Snowball Lie', 'Comedy of Errors', 'The Mix-up', 'Embarrassing Reveal', 'Wrong Place, Wrong Time', 'The Overcomplicated Plan', 'The Big Misunderstanding', 'Double Entendre', 'Miscommunication Humor', 'Slapstick', 'Over-the-top reactions', 'The Costume Fail', 'Prop Humor', 'The Hidden Eavesdropper', 'The Wrong Room', 'The Misplaced Confidence', 'Accidental Offense', 'Stuck together', 'Ridiculous Excuses', 'Everything Goes Wrong', 'The Annoying Relative', 'The Talking Animal or Object', 'Breaking the Fourth Wall', 'Cartoon Logic', 'Overly Specific Rules', 'Absurd Explanations'],

    CrimeOrMystery: ['The Cozy Mystery', 'Defective Detective', 'Blackmail', 'The Cat and Mouse Game', 'The Locked Room Mystery', 'The Heist', 'The Whodunnit', 'The Red Herring', 'The Cover-Up', 'The Wrongly Accused', 'The Double Cross', 'Revenge Crime', 'The Inside Job', 'The Cold Case', 'The Frame Up', 'The Criminal Mastermind', 'The Escaped Convict', 'The Hard Boiled Detective', 'The Femme Fatale', 'The By-The-Book Cop', 'The Dirty Cop', 'The Reluctant Criminal', 'The Criminal with a Code', 'The Amoral Mastermind', 'The Vigilante', 'The Innocent Bystander', 'The Mole', 'The Hapless Criminal', 'The Sociopath', 'The Rookie Cop', 'The Undercover Agent', 'The Reformed Criminal', 'The Seedy Underbelly', 'The Isolated Mansion', 'The Back Alley', "The Mob's Turf", 'The Prison', 'The Jewel Heist', 'The Bank Robbery', 'The Kidnapping', 'The Hit Job', 'The Drug Trade', 'The Con Game', 'The Cyber Crime', 'The Art Theft', 'The Political Scandal', 'The Unexpected Ally', 'The Crime Gone Wrong', 'The Thin Line Between Good and Evil', 'The Murder Mystery'],

    Drama: ['The Cost of Ambition', 'The Power of Forgiveness', 'The Burden of Legacy', 'The Price of Truth', 'The Fragility of Relationships', 'The Impact of Trauma', 'The Duality of Man', 'The Nature of Sacrifice', 'The Search of Identity', 'The Struggle of Redemption'],

    Fantasy: ['The Medieval Setting', 'The Magical Forest', 'The Ancient Ruins', 'The Hidden Kingdom', 'The Floating City/Island', 'The Forbidden Zone', 'The Nexus of Magic', 'The Warring Kingdoms', 'The Dual Worlds', 'The Wise Old Mentor', 'The Evil Overlord', 'The Anti-Hero', 'The Naive Farm Boy/Girl', "The Dark Lord's Minion", 'The Lost Heir', 'The Magician or Wizard', 'The Warrior Prince/Princess', 'The Shape Shifter', 'The Loyal Companion', 'The Cursed One', 'The Trickster', 'The Fallen Hero', "The Hero's Journey", 'The Prophecy', 'The Quest', "The Chosen's One Training", 'The Ultimate Showdown', 'The Ancient Evil Awakens', 'The Magic School', 'The Lost Artifact', 'The Tournament Arc', 'The Time Loop', 'The Forbidden Spell', 'The Magic is Dying', 'The Elemental Powers', 'The Bloodline Gift', 'The Pact with a Demon', 'The Mana Drain', 'The Sentient Weapon', 'The Rune of Glyph Magic', 'The Magical Bond', 'Dragons', 'Elves', 'Orcs', 'Dwarves', 'THe Fae Realem', 'The Magical Familiar', 'The Undead Army', 'The Ancient Behemoth', 'The Chimera', 'The Talking Animal', 'The Nobel Beast', 'The Monstrous Horde', 'The Corruption Arc', 'The Triumph of Hope', 'The Nature vs Civilization Conflict', 'The Cycle of Rebirth', 'The Importance of Friendship', 'The Loss of Innocence', 'The Legacy of Heroes', 'The Quest For Knowledge'],

    Historical: ['The Poison Plot', 'Th Spy in Court', 'The Ancient Prophecy', 'The Hidden Treasure', 'The Double Agent', 'The Forbidden Book', 'The Disguised Rebel', 'The Unsolved Mystery', 'The Shadowy Conspiracy', 'The Rise and Fall', 'The March of Progress', 'The Cost of War', 'The Clash of Cultures', 'The Road to Discovery', 'The Legacy of Family', 'The Survival of Tradition', 'The Class Struggle', 'The Religious Persecution', 'The Succession Crisis', 'The Forbidden Knowledge', 'The Colonial Rebellion', 'The Feudal Power Play', 'The Revolution', 'The Invasion', 'The Witch Hunt', 'The Trade War', 'The Chivalrous Knight', 'The Feisty Peasent', 'The Ruthless Nobel', 'The Idealistic Revolutionary', 'The Disgraced Aristocrat', 'The Scheming Advisor', 'The Ingenious Inventor', 'The Mystic or Healer'],

    Horror: ['The Haunted House', 'The Isolated Cabin', 'The Abandoned Asylum', 'The Creepy Small Town', 'The Foggy Graveyard', 'The Dark Forest', 'The Old Hotel', 'The Mirror Realm', 'The Forbidden Basement/Attic', 'The Ghost Town', 'The Fina; Girl/Guy', 'The Mad Scientist', 'The Creepy Child', 'The Skeptic', 'The Sinister Old Person', 'The Possessed', 'The Monster Hunter', 'The Innocent Victim', 'The Evil Entity', 'The Summoning Ritual', 'The Cursed Object', 'The Creepy Phone Call', 'The Hidden Secret', 'The Sudden Disappearance', 'The Unexplained Phenomenon', 'The Creepy Warning', 'The Survival Game', 'The Found Footage', 'The Unstoppable Killer', 'The Eldritch Abomination', 'The Ghostly Apparition', 'The Killer Animal', 'The Doppelganger', 'The Jump Scare', 'The Unseen Threat', 'The Shadowy Figure', 'The Bloody Message', 'The Sacrificial Lamb', 'The Last Stand', 'The False Escape', "'It's Not Over'", 'The Sudden Gore', 'The Possessed Object', 'Ouija Board Gone Wrong', 'The Poltergiest', 'The Curse', 'The Wailing Ghost', 'The Supernatural Mark', 'The Living Shadows', 'The Ancient Tome', 'Th Sealed Evil'],

    SciFi: ['The Spacefaring Civilization', 'The Dystopian Future', 'The Utopian Society', 'The Alien World', 'The Abandoned Space Station', 'The Post-Apocolyptic Wasteland', 'The Virtual Reality World', 'The Parallel Universe', 'The Deep Space Outpost', 'Faster-than-light travel', 'AI (Artificial Intelligence)', 'Time Travel', 'Robots and Androids', 'Teleportation', 'Mind Uploading', 'Cybernetic Enhancements', 'Nanotechnology', 'Cloaking Technology', 'Energy Weapons', 'The Rogue Pilot', 'The Mysterious Alien', 'The Mad Scientist', 'The Cyborg', 'The AI Companion', 'The Ruthless Corporatist', 'The Space Pirate', 'The Time Traveller', 'The Intergalactic War', 'The AI Uprising', 'The Alien Invasion', 'The Ethical Dilemma', 'The Space Race', 'The Rogue AI', 'The Genetic Experiment Gone Wrong', 'The Galactic Empire', 'The Hive Mind', 'The Benevolent Mentor Race', 'The Predatory Alien', 'The Alien Refugee', 'The Shape-Shifter', 'The Ancient Alien Civilization', 'The Warlike Species', 'The Symbiotic Alien', 'The Alien Ambassador', 'The Space Bar', 'The Alien Ruins', 'The Alien Sky'],

    Thriller: ['The Ticking Clock', 'The Conspiracy', 'The Innocent Framed', 'The Twist Ending', 'The Cover-up', 'The Hidden Agenda', 'The Hidden Threat', 'The Claustrophobic Trap', 'The Escalating Stakes', 'The Phone Call from the Killer', 'The Constant Surveillance', 'Trust No One', 'The Blurred Lines of Morality', 'Revenge', 'Obsession', 'Isolation', 'Paranoia', 'Sacrafice'],

    Western: ['The Lone Gunslinger', 'The Outlaw', 'The Sheriff', 'The Bounty Hunter', 'The Rancher', 'The Saloon Girl/Guy', 'The Grizzled Prospector', 'The Native Warrior', 'The Damsel in Distress', 'The Wealthy Landowner', 'The Land Grab', 'The Range War', 'The Bank Heist', 'The Revenge Quest', 'The Train Robbery', 'The Duel at High Noon', 'The Seige', 'The Cattle Drive Gone Wrong', 'The Forced Aliance', 'The Cowboy Hats and Spurs', 'The Campfire Scene', 'The Bar Brawl']

}

export default Tropes

